from datetime import datetime
from pydantic import BaseModel, Field, field_validator

class ComplaintRequest(BaseModel):
    complaint: str = Field(..., description="The industrial equipment complaint description in natural language.")

    @field_validator("complaint")
    @classmethod
    def validate_complaint_text(cls, value: str) -> str:
        # Strip trailing/leading whitespace and validate content presence
        trimmed = value.strip()
        if not trimmed:
            raise ValueError("Complaint text cannot be empty or solely whitespace.")
        if len(trimmed) < 10:
            raise ValueError("Complaint text must be at least 10 characters in length.")
        return trimmed

class ComplaintResponse(BaseModel):
    ticket_id: str = Field(..., description="Unique generated ticket identifier in TKT-YYYY-XXXX format.")
    original_complaint: str = Field(..., description="The original natural language complaint string.")
    issue_type: str = Field(..., description="Classification category (Electrical, Mechanical, Sensor, Unknown).")
    priority: str = Field(..., description="Assigned priority level (Low, Medium, High).")
    summary: str = Field(..., description="Concise diagnostic summary generated by LLM.")
    created_at: datetime = Field(..., description="Timestamp representing when the ticket was generated and stored.")

    class Config:
        from_attributes = True
